### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by Pablo2048** [prevwong/drooltip.js#1]
Hi and thank You for great library. Unfortunately it didn't work under IE (tested on version 11.0.9600.18097). In IE console there is error SCRIPT1003 detected at line 50 in drooltip.js at row 8 - ':' character expected. It seems like this problem http://stackoverflow.com/questions/35808557/javascript-ajax-script1003-expected-in-ie-11

**Comment by prevwong** [comment]
Hey, firstly thanks a lot for reporting this issue! I will look into it as soon as I can!  
Cheers :)

**Comment by samir-kamble** [comment]
Any solution on this till now? I am also facing the same issue.

**Comment by prevwong** [comment]
Hi there. So sorry for not updating on this, have been caught up with a lot of work at the moment. But anyways, I have figured out what was causing the issue; It's likely due to Drooltip having some ES6 code which is unsupported in IE 11. 

In the case of SCRIPT1003, the issue is related to objects. Normally, in objects, there should be a key and a value pair. In ES6, you are allowed to just add a variable into an object without having to specify it's key. As a result, the key is automatically set to the variables name. Take a part of Drooltip's code for example:

`this.tooltips[i] = { tooltip, options };`  which is ES6 compliant and is equivalent to
`this.tooltips[i] = { "tooltip" : tooltip,  "options" : options };`

The former is what's written in Drooltip currently and is supported by most modern browsers. However, the latter is what needs to be done in order to support older browsers such as IE11.

I will try to update the code to be more backwards compatible when I can.

**Comment by prevwong** [comment]
@Pablo2048 @samir-kamble Hey guys, support for IE-11 is here! Sorry again for the wait.

**Comment by Pablo2048** [comment]
@prevwong Thank You very much...
